### PR TITLE
More BRMS & BPM Suite demo project listings

### PR DESCRIPTION
**Pull request by eschabell**
Adds two realtime decision server examples and business resource planner demo project.

### CODE REVIEW

**Comment by eschabell** [comment]
Adding more bpm suite demo project to developer.redhat.com.

**Comment by eschabell** [comment]
Added more projects, bpm suite to add to developer site.

**Comment by eschabell** [comment]
Added another install demo for bpmsuite.

**Comment by eschabell** [comment]
Final bpm suite projects added.

**Comment by paulrobinson** [comment]
Sorry, it needs a rebase. I've added back in the multi-product demo. Checking to make sure we've fixed that issue...

**Comment by paulrobinson** [comment]
It's ok, I fixed it with: https://github.com/jboss-developer/jboss-developer-demos/pull/19

**Pull request closed without merging**
