### PR TITLE
Added Red Hat Demo Central CDK, OpenShift and Red Hat Cloud Suite demos.

### PR DESCRIPTION
**Pull request by eschabell**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Can you rebase please?

**Comment by eschabell** [comment]
Can you be more specific? I tried to rebase but nothing changes:
1. git remote add upstream https://github.com/jboss-developer/jboss-developer-demos.git
2. git fetch upstream
3. git checkout master
4. git rebase upstream/master
5. Fixed conflicts in demo.yaml file.
6. git co -a -m "Rebased demos.yaml on fork."
7. git push -f origin master

Now a new PR gives conflicts....

**Comment by paulrobinson** [comment]
I'm not sure what you did wrong. I think you've had this issue before?

Anyway, for simple edits like this you can use the GitHub web interface to easily make edits. Just click 'edit' on the file (when browsing the files on the _upstream_ repo, not your fork) and it will guide you through the process of making a commit and raising a PR.

That is what I did to make: https://github.com/jboss-developer/jboss-developer-demos/pull/23

Can you check the PR above that I made for you?

**Comment by eschabell** [comment]
Thanks, will check the other one.

**Pull request closed without merging**
